### ISSUE TITLE
chemixAppModel sometimes becomes unavailable

### ISSUE THREAD

**Issue by macduy** [macduy/chemix#13]
https://sentry.io/chemix/chemix/issues/245749504/

```
TypeError: chemixAppModel.style(...) is undefined
  at None (/js/app.js:767:17)
  at n.event.dispatch (/jquery-2.2.2.min.js:3:7485)
  at n.event.add/r.handle (/jquery-2.2.2.min.js:3:5603)
  at .trigger (/jquery-2.2.2.min.js:4:4834)
  at .trigger/< (/jquery-2.2.2.min.js:4:5381)
...
(13 additional frame(s) were not displayed)
```

**Comment by macduy** [comment]
https://sentry.io/chemix/chemix/issues/245801173/

**Comment by macduy** [comment]
https://sentry.io/chemix/chemix/issues/245801137/
