### ISSUE TITLE
chemixFlashApp (JS->Flash object) is undefined

### ISSUE THREAD

**Issue by macduy** [macduy/chemix#14]
https://sentry.io/chemix/chemix/issues/245801137/

```
ReferenceError: 'chemixFlashApp' is undefined
  at self.addApparatus (/js/app.js:396:5)
  at Anonymous function (/ajax/libs/knockout/3.4.0/knockout-min.js:89:439)
  at n.event.dispatch (/jquery-2.2.2.min.js:3:7481)
  at r.handle (/jquery-2.2.2.min.js:3:5547)
```

**Comment by macduy** [comment]
https://sentry.io/chemix/chemix/issues/245801173/
